name: Actividad_3_devops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Setup
      run: |
        docker build -t flask-app ./app

    - name: Set up Docker Compose
      run: |
        docker compose -f docker-compose.yml up -d

    - name: Wait for app
      run: sleep 10

    - name: Verify Flask app is running
      run: |
        curl http://localhost:5000