version: 0.2

phases:
  install:
  runtime-versions:
    python:3.9
  build:
    commands:
      -echo "ejecuando pruebas"
      -pytest tests/
  
  post_build:
    commands:
      -echo "construccion finalizada con exito"